
@address=identity.k8shell-test
#@address=localhost

### individual user
http://{{address}}:9090/api/v1/users/bruckins
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

### lookup by token
POST http://{{address}}:9090/api/v1/users/lookup/token
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

{
  "token": "1b60c2d2d13f462eef6f59cfe1d6a446845fe62ac325c91a38dc67cd3e5c679f"
}


### Get credentials
http://{{address}}:9090/api/v1/users/vitvatom/credentials
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

### Add credentials
POST http://{{address}}:9090/api/v1/users/bruckins/credentials
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

{
  "service_name": "registry",
  "service_url": "fitcr.ksi.in.fit.cvut.cz",
  "external_id": "admin",
  "external_token": "Harbor94ek1"
}

### Delete credentials
DELETE http://{{address}}:9090/api/v1/users/vitvatom/credentials/3
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c


### all users
http://{{address}}:9090/api/v1/users
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

### authenticate user
POST http://{{address}}:9090/api/v1/users/vitvatom/authenticate
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

{
    "public_key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD0WFyteR7SWAKgAtoiyRon96zG48ew52uXmlMK1nmY9Cb2ekwQWvgjTaF+AZ2ZjwS+BHrvCDsRDym/PMZ0SyHUyX9vLhKeIqZkNTpI0MB3RRQ8zY1IxdLQny7uSr5pZab5r7pEMsDmoEOHbZeeFKi1f3R4c4fgvqj2pBHIRiIMQUlVqeBbvVcOHVWddJMQAssV8sHjdq2upxr/SctM7qH9WMX8R1sh4npOVFI3zUkVDIO+4xmZpE0ihKf6vLZt7bTrXfP7db6jTcZX6BKCJA1CVuSnll+O+lYzunUNQyw8D++wrGvEkrXGowgHVotC2PS5JPVsnMzrNrCnG8vEgt3 Tomáš Vitvar (gitlab.fit.cvut.cz)"
}

### create a session for user
POST http://{{address}}:9090/api/v1/users/vitvatom/sessions
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c

{
  "client_ip": "192.168.1.10",
  "proxy_id": "abcdefg",
  "proxy_pid": 12345,
  "workspace": "test"
}

### get all sessions for user
GET http://{{address}}:9090/api/v1/users/vitvatom/sessions
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

### get last session for user
GET http://{{address}}:9090/api/v1/users/vitvatom/sessions?reverse=true&limit=1
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json

### get custom blueprint
#GET http://localhost:9090/api/v1/blueprints/lookup?userstr=bruckins~repo=k8shell-io/common
GET http://{{address}}:9090/api/v1/blueprints/lookup?userstr=bruckins~repo%3Dk8shell-io%2Fcommon
Authorization: Bearer 6f16982b35ac2168f86c7978b7b42967538939b063598346139e0963510c
Content-Type: application/json
