syntax = "proto3";

package identity;

option go_package = "github.com/k8shell-io/identity/pkg/api/identitypb;identitypb";

import "common/pkg/gapi/common.proto";
import "pkg/api/types.proto";
 
// *** Identity service 

service IdentityService {
  // User Management
  rpc FindUser (types.FindUserRequest) returns (common.User);
  rpc GetUsers (types.GetUsersRequest) returns (types.UserList);

  // OAuth2 Onboarding 
  rpc GetUserOnboardCapability (types.Username) returns (common.UserOnboardCapability);
  rpc OnboardUserDeviceFlow (types.Username) returns (common.OnboardUserDeviceFlow);
  rpc OnboardUserWebFlow (types.OnboardUserWebFlowRequest) returns (common.OnboardUserWebFlow);
  rpc CompleteUserWebFlow (types.CompleteUserWebFlowRequest) returns (common.User);
  
  // Authentication
  rpc AuthUserPublicKey (types.AuthUserPublicKeyRequest) returns (types.AuthUserResponse);

  // Repository content
  rpc GetBlueprintByUserStr (types.UserStr) returns (types.Blueprint);
  rpc ResolvePullRequestToRef (types.RepoPullRequestRequest) returns (types.RepoRefResponse);
  // External Credentials
  rpc GetUserCredentials (types.Username) returns (GetUserCredentialsResponse);
  rpc AddUserCredential (common.ExternalCredential) returns (AddUserCredentialResponse);
  rpc UpdateUserCredential (common.ExternalCredential) returns (UpdateUserCredentialResponse);
  rpc DeleteUserCredential (DeleteUserCredentialRequest) returns (DeleteUserCredentialResponse);
}
 
// *** Messages ***   

// External Credential messages

message GetUserCredentialsResponse {
  repeated common.ExternalCredential credentials = 1;
}

message AddUserCredentialResponse {
  common.ExternalCredential credential = 1;
}

message UpdateUserCredentialResponse {
  common.ExternalCredential credential = 1;
}

message DeleteUserCredentialRequest {
  uint32 id = 1;
}

message DeleteUserCredentialResponse {
  bool success = 1;
}
