apiVersion: v1
kind: Service
metadata:
  name: identity-api  
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.ClusterIP.port }}
      targetPort: 9090