// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/api/identity.proto

package identitypb

import (
	context "context"
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	typespb "github.com/k8shell-io/identity/pkg/api/typespb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_FindUser_FullMethodName                 = "/identity.IdentityService/FindUser"
	IdentityService_GetUsers_FullMethodName                 = "/identity.IdentityService/GetUsers"
	IdentityService_GetUserOnboardCapability_FullMethodName = "/identity.IdentityService/GetUserOnboardCapability"
	IdentityService_OnboardUserDeviceFlow_FullMethodName    = "/identity.IdentityService/OnboardUserDeviceFlow"
	IdentityService_OnboardUserWebFlow_FullMethodName       = "/identity.IdentityService/OnboardUserWebFlow"
	IdentityService_CompleteUserWebFlow_FullMethodName      = "/identity.IdentityService/CompleteUserWebFlow"
	IdentityService_AuthUserPublicKey_FullMethodName        = "/identity.IdentityService/AuthUserPublicKey"
	IdentityService_GetBlueprintByUserStr_FullMethodName    = "/identity.IdentityService/GetBlueprintByUserStr"
	IdentityService_ResolvePullRequestToRef_FullMethodName  = "/identity.IdentityService/ResolvePullRequestToRef"
	IdentityService_GetUserCredentials_FullMethodName       = "/identity.IdentityService/GetUserCredentials"
	IdentityService_AddUserCredential_FullMethodName        = "/identity.IdentityService/AddUserCredential"
	IdentityService_UpdateUserCredential_FullMethodName     = "/identity.IdentityService/UpdateUserCredential"
	IdentityService_DeleteUserCredential_FullMethodName     = "/identity.IdentityService/DeleteUserCredential"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService provides operations for user management, authentication,
// onboarding, and external credential management.
type IdentityServiceClient interface {
	// FindUser retrieves a user by username. It can be used for authentication and user lookup.
	FindUser(ctx context.Context, in *typespb.FindUserRequest, opts ...grpc.CallOption) (*commonpb.User, error)
	// GetUsers retrieves a list of users with pagination support.
	GetUsers(ctx context.Context, in *typespb.GetUsersRequest, opts ...grpc.CallOption) (*typespb.UserList, error)
	// GetUserOnboardCapability checks if the identity provider supports onboarding and returns the capability details.
	GetUserOnboardCapability(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.UserOnboardCapability, error)
	// OnboardUserDeviceFlow initiates the device flow onboarding process for a user.
	OnboardUserDeviceFlow(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.OnboardUserDeviceFlow, error)
	// OnboardUserWebFlow initiates the web flow onboarding process for a user.
	OnboardUserWebFlow(ctx context.Context, in *typespb.OnboardUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.OnboardUserWebFlow, error)
	// CompleteUserWebFlow completes the web flow onboarding process using the provided state and code.
	CompleteUserWebFlow(ctx context.Context, in *typespb.CompleteUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.User, error)
	// AuthUserPublicKey authenticates a user using a public key and returns the authentication result
	// along with user details if valid.
	AuthUserPublicKey(ctx context.Context, in *typespb.AuthUserPublicKeyRequest, opts ...grpc.CallOption) (*typespb.AuthUserResponse, error)
	// GetBlueprintByUserStr retrieves a blueprint associated with a user string identifier.
	GetBlueprintByUserStr(ctx context.Context, in *typespb.UserStr, opts ...grpc.CallOption) (*typespb.Blueprint, error)
	// ResolvePullRequestToRef resolves a pull request to a repository reference (e.g., branch or commit).
	ResolvePullRequestToRef(ctx context.Context, in *typespb.RepoPullRequestRequest, opts ...grpc.CallOption) (*typespb.RepoRefResponse, error)
	// GetUserCredentials retrieves all external credentials associated with a user.
	GetUserCredentials(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*GetUserCredentialsResponse, error)
	// AddUserCredential adds a new external credential for a user.
	AddUserCredential(ctx context.Context, in *commonpb.ExternalCredential, opts ...grpc.CallOption) (*AddUserCredentialResponse, error)
	// UpdateUserCredential updates an existing external credential for a user.
	UpdateUserCredential(ctx context.Context, in *commonpb.ExternalCredential, opts ...grpc.CallOption) (*UpdateUserCredentialResponse, error)
	// DeleteUserCredential deletes an external credential by its ID.
	DeleteUserCredential(ctx context.Context, in *DeleteUserCredentialRequest, opts ...grpc.CallOption) (*DeleteUserCredentialResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) FindUser(ctx context.Context, in *typespb.FindUserRequest, opts ...grpc.CallOption) (*commonpb.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.User)
	err := c.cc.Invoke(ctx, IdentityService_FindUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUsers(ctx context.Context, in *typespb.GetUsersRequest, opts ...grpc.CallOption) (*typespb.UserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(typespb.UserList)
	err := c.cc.Invoke(ctx, IdentityService_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserOnboardCapability(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.UserOnboardCapability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.UserOnboardCapability)
	err := c.cc.Invoke(ctx, IdentityService_GetUserOnboardCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) OnboardUserDeviceFlow(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.OnboardUserDeviceFlow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.OnboardUserDeviceFlow)
	err := c.cc.Invoke(ctx, IdentityService_OnboardUserDeviceFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) OnboardUserWebFlow(ctx context.Context, in *typespb.OnboardUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.OnboardUserWebFlow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.OnboardUserWebFlow)
	err := c.cc.Invoke(ctx, IdentityService_OnboardUserWebFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) CompleteUserWebFlow(ctx context.Context, in *typespb.CompleteUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.User)
	err := c.cc.Invoke(ctx, IdentityService_CompleteUserWebFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) AuthUserPublicKey(ctx context.Context, in *typespb.AuthUserPublicKeyRequest, opts ...grpc.CallOption) (*typespb.AuthUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(typespb.AuthUserResponse)
	err := c.cc.Invoke(ctx, IdentityService_AuthUserPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetBlueprintByUserStr(ctx context.Context, in *typespb.UserStr, opts ...grpc.CallOption) (*typespb.Blueprint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(typespb.Blueprint)
	err := c.cc.Invoke(ctx, IdentityService_GetBlueprintByUserStr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ResolvePullRequestToRef(ctx context.Context, in *typespb.RepoPullRequestRequest, opts ...grpc.CallOption) (*typespb.RepoRefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(typespb.RepoRefResponse)
	err := c.cc.Invoke(ctx, IdentityService_ResolvePullRequestToRef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserCredentials(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*GetUserCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCredentialsResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) AddUserCredential(ctx context.Context, in *commonpb.ExternalCredential, opts ...grpc.CallOption) (*AddUserCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserCredentialResponse)
	err := c.cc.Invoke(ctx, IdentityService_AddUserCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UpdateUserCredential(ctx context.Context, in *commonpb.ExternalCredential, opts ...grpc.CallOption) (*UpdateUserCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserCredentialResponse)
	err := c.cc.Invoke(ctx, IdentityService_UpdateUserCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeleteUserCredential(ctx context.Context, in *DeleteUserCredentialRequest, opts ...grpc.CallOption) (*DeleteUserCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserCredentialResponse)
	err := c.cc.Invoke(ctx, IdentityService_DeleteUserCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService provides operations for user management, authentication,
// onboarding, and external credential management.
type IdentityServiceServer interface {
	// FindUser retrieves a user by username. It can be used for authentication and user lookup.
	FindUser(context.Context, *typespb.FindUserRequest) (*commonpb.User, error)
	// GetUsers retrieves a list of users with pagination support.
	GetUsers(context.Context, *typespb.GetUsersRequest) (*typespb.UserList, error)
	// GetUserOnboardCapability checks if the identity provider supports onboarding and returns the capability details.
	GetUserOnboardCapability(context.Context, *typespb.Username) (*commonpb.UserOnboardCapability, error)
	// OnboardUserDeviceFlow initiates the device flow onboarding process for a user.
	OnboardUserDeviceFlow(context.Context, *typespb.Username) (*commonpb.OnboardUserDeviceFlow, error)
	// OnboardUserWebFlow initiates the web flow onboarding process for a user.
	OnboardUserWebFlow(context.Context, *typespb.OnboardUserWebFlowRequest) (*commonpb.OnboardUserWebFlow, error)
	// CompleteUserWebFlow completes the web flow onboarding process using the provided state and code.
	CompleteUserWebFlow(context.Context, *typespb.CompleteUserWebFlowRequest) (*commonpb.User, error)
	// AuthUserPublicKey authenticates a user using a public key and returns the authentication result
	// along with user details if valid.
	AuthUserPublicKey(context.Context, *typespb.AuthUserPublicKeyRequest) (*typespb.AuthUserResponse, error)
	// GetBlueprintByUserStr retrieves a blueprint associated with a user string identifier.
	GetBlueprintByUserStr(context.Context, *typespb.UserStr) (*typespb.Blueprint, error)
	// ResolvePullRequestToRef resolves a pull request to a repository reference (e.g., branch or commit).
	ResolvePullRequestToRef(context.Context, *typespb.RepoPullRequestRequest) (*typespb.RepoRefResponse, error)
	// GetUserCredentials retrieves all external credentials associated with a user.
	GetUserCredentials(context.Context, *typespb.Username) (*GetUserCredentialsResponse, error)
	// AddUserCredential adds a new external credential for a user.
	AddUserCredential(context.Context, *commonpb.ExternalCredential) (*AddUserCredentialResponse, error)
	// UpdateUserCredential updates an existing external credential for a user.
	UpdateUserCredential(context.Context, *commonpb.ExternalCredential) (*UpdateUserCredentialResponse, error)
	// DeleteUserCredential deletes an external credential by its ID.
	DeleteUserCredential(context.Context, *DeleteUserCredentialRequest) (*DeleteUserCredentialResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) FindUser(context.Context, *typespb.FindUserRequest) (*commonpb.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUser not implemented")
}
func (UnimplementedIdentityServiceServer) GetUsers(context.Context, *typespb.GetUsersRequest) (*typespb.UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserOnboardCapability(context.Context, *typespb.Username) (*commonpb.UserOnboardCapability, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOnboardCapability not implemented")
}
func (UnimplementedIdentityServiceServer) OnboardUserDeviceFlow(context.Context, *typespb.Username) (*commonpb.OnboardUserDeviceFlow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardUserDeviceFlow not implemented")
}
func (UnimplementedIdentityServiceServer) OnboardUserWebFlow(context.Context, *typespb.OnboardUserWebFlowRequest) (*commonpb.OnboardUserWebFlow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardUserWebFlow not implemented")
}
func (UnimplementedIdentityServiceServer) CompleteUserWebFlow(context.Context, *typespb.CompleteUserWebFlowRequest) (*commonpb.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteUserWebFlow not implemented")
}
func (UnimplementedIdentityServiceServer) AuthUserPublicKey(context.Context, *typespb.AuthUserPublicKeyRequest) (*typespb.AuthUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUserPublicKey not implemented")
}
func (UnimplementedIdentityServiceServer) GetBlueprintByUserStr(context.Context, *typespb.UserStr) (*typespb.Blueprint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlueprintByUserStr not implemented")
}
func (UnimplementedIdentityServiceServer) ResolvePullRequestToRef(context.Context, *typespb.RepoPullRequestRequest) (*typespb.RepoRefResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePullRequestToRef not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserCredentials(context.Context, *typespb.Username) (*GetUserCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCredentials not implemented")
}
func (UnimplementedIdentityServiceServer) AddUserCredential(context.Context, *commonpb.ExternalCredential) (*AddUserCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserCredential not implemented")
}
func (UnimplementedIdentityServiceServer) UpdateUserCredential(context.Context, *commonpb.ExternalCredential) (*UpdateUserCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserCredential not implemented")
}
func (UnimplementedIdentityServiceServer) DeleteUserCredential(context.Context, *DeleteUserCredentialRequest) (*DeleteUserCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserCredential not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call pancis, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.FindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_FindUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).FindUser(ctx, req.(*typespb.FindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUsers(ctx, req.(*typespb.GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserOnboardCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserOnboardCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserOnboardCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserOnboardCapability(ctx, req.(*typespb.Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_OnboardUserDeviceFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).OnboardUserDeviceFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_OnboardUserDeviceFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).OnboardUserDeviceFlow(ctx, req.(*typespb.Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_OnboardUserWebFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.OnboardUserWebFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).OnboardUserWebFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_OnboardUserWebFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).OnboardUserWebFlow(ctx, req.(*typespb.OnboardUserWebFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_CompleteUserWebFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.CompleteUserWebFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CompleteUserWebFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CompleteUserWebFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CompleteUserWebFlow(ctx, req.(*typespb.CompleteUserWebFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_AuthUserPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.AuthUserPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).AuthUserPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_AuthUserPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).AuthUserPublicKey(ctx, req.(*typespb.AuthUserPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetBlueprintByUserStr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.UserStr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetBlueprintByUserStr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetBlueprintByUserStr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetBlueprintByUserStr(ctx, req.(*typespb.UserStr))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ResolvePullRequestToRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.RepoPullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ResolvePullRequestToRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ResolvePullRequestToRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ResolvePullRequestToRef(ctx, req.(*typespb.RepoPullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserCredentials(ctx, req.(*typespb.Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_AddUserCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.ExternalCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).AddUserCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_AddUserCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).AddUserCredential(ctx, req.(*commonpb.ExternalCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UpdateUserCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.ExternalCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UpdateUserCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UpdateUserCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UpdateUserCredential(ctx, req.(*commonpb.ExternalCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeleteUserCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeleteUserCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DeleteUserCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeleteUserCredential(ctx, req.(*DeleteUserCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindUser",
			Handler:    _IdentityService_FindUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _IdentityService_GetUsers_Handler,
		},
		{
			MethodName: "GetUserOnboardCapability",
			Handler:    _IdentityService_GetUserOnboardCapability_Handler,
		},
		{
			MethodName: "OnboardUserDeviceFlow",
			Handler:    _IdentityService_OnboardUserDeviceFlow_Handler,
		},
		{
			MethodName: "OnboardUserWebFlow",
			Handler:    _IdentityService_OnboardUserWebFlow_Handler,
		},
		{
			MethodName: "CompleteUserWebFlow",
			Handler:    _IdentityService_CompleteUserWebFlow_Handler,
		},
		{
			MethodName: "AuthUserPublicKey",
			Handler:    _IdentityService_AuthUserPublicKey_Handler,
		},
		{
			MethodName: "GetBlueprintByUserStr",
			Handler:    _IdentityService_GetBlueprintByUserStr_Handler,
		},
		{
			MethodName: "ResolvePullRequestToRef",
			Handler:    _IdentityService_ResolvePullRequestToRef_Handler,
		},
		{
			MethodName: "GetUserCredentials",
			Handler:    _IdentityService_GetUserCredentials_Handler,
		},
		{
			MethodName: "AddUserCredential",
			Handler:    _IdentityService_AddUserCredential_Handler,
		},
		{
			MethodName: "UpdateUserCredential",
			Handler:    _IdentityService_UpdateUserCredential_Handler,
		},
		{
			MethodName: "DeleteUserCredential",
			Handler:    _IdentityService_DeleteUserCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/identity.proto",
}
