// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/api/identity.proto

package identitypb

import (
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	typespb "github.com/k8shell-io/identity/pkg/api/typespb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserCredentialsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Credentials   []*commonpb.ExternalCredential `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCredentialsResponse) Reset() {
	*x = GetUserCredentialsResponse{}
	mi := &file_pkg_api_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCredentialsResponse) ProtoMessage() {}

func (x *GetUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_identity_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserCredentialsResponse) GetCredentials() []*commonpb.ExternalCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type AddUserCredentialResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Credential    *commonpb.ExternalCredential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserCredentialResponse) Reset() {
	*x = AddUserCredentialResponse{}
	mi := &file_pkg_api_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserCredentialResponse) ProtoMessage() {}

func (x *AddUserCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserCredentialResponse.ProtoReflect.Descriptor instead.
func (*AddUserCredentialResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_identity_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserCredentialResponse) GetCredential() *commonpb.ExternalCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type UpdateUserCredentialResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Credential    *commonpb.ExternalCredential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserCredentialResponse) Reset() {
	*x = UpdateUserCredentialResponse{}
	mi := &file_pkg_api_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserCredentialResponse) ProtoMessage() {}

func (x *UpdateUserCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserCredentialResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserCredentialResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_identity_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserCredentialResponse) GetCredential() *commonpb.ExternalCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type DeleteUserCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserCredentialRequest) Reset() {
	*x = DeleteUserCredentialRequest{}
	mi := &file_pkg_api_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserCredentialRequest) ProtoMessage() {}

func (x *DeleteUserCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserCredentialRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_identity_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserCredentialRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserCredentialResponse) Reset() {
	*x = DeleteUserCredentialResponse{}
	mi := &file_pkg_api_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserCredentialResponse) ProtoMessage() {}

func (x *DeleteUserCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserCredentialResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_identity_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_api_identity_proto protoreflect.FileDescriptor

const file_pkg_api_identity_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/api/identity.proto\x12\bidentity\x1a(.proto_deps/common/pkg/gapi/common.proto\x1a\x13pkg/api/types.proto\"Z\n" +
	"\x1aGetUserCredentialsResponse\x12<\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1a.common.ExternalCredentialR\vcredentials\"W\n" +
	"\x19AddUserCredentialResponse\x12:\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1a.common.ExternalCredentialR\n" +
	"credential\"Z\n" +
	"\x1cUpdateUserCredentialResponse\x12:\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1a.common.ExternalCredentialR\n" +
	"credential\"-\n" +
	"\x1bDeleteUserCredentialRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"8\n" +
	"\x1cDeleteUserCredentialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xeb\a\n" +
	"\x0fIdentityService\x120\n" +
	"\bFindUser\x12\x16.types.FindUserRequest\x1a\f.common.User\x123\n" +
	"\bGetUsers\x12\x16.types.GetUsersRequest\x1a\x0f.types.UserList\x12J\n" +
	"\x18GetUserOnboardCapability\x12\x0f.types.Username\x1a\x1d.common.UserOnboardCapability\x12G\n" +
	"\x15OnboardUserDeviceFlow\x12\x0f.types.Username\x1a\x1d.common.OnboardUserDeviceFlow\x12R\n" +
	"\x12OnboardUserWebFlow\x12 .types.OnboardUserWebFlowRequest\x1a\x1a.common.OnboardUserWebFlow\x12F\n" +
	"\x13CompleteUserWebFlow\x12!.types.CompleteUserWebFlowRequest\x1a\f.common.User\x12M\n" +
	"\x11AuthUserPublicKey\x12\x1f.types.AuthUserPublicKeyRequest\x1a\x17.types.AuthUserResponse\x129\n" +
	"\x15GetBlueprintByUserStr\x12\x0e.types.UserStr\x1a\x10.types.Blueprint\x12P\n" +
	"\x17ResolvePullRequestToRef\x12\x1d.types.RepoPullRequestRequest\x1a\x16.types.RepoRefResponse\x12K\n" +
	"\x12GetUserCredentials\x12\x0f.types.Username\x1a$.identity.GetUserCredentialsResponse\x12T\n" +
	"\x11AddUserCredential\x12\x1a.common.ExternalCredential\x1a#.identity.AddUserCredentialResponse\x12Z\n" +
	"\x14UpdateUserCredential\x12\x1a.common.ExternalCredential\x1a&.identity.UpdateUserCredentialResponse\x12e\n" +
	"\x14DeleteUserCredential\x12%.identity.DeleteUserCredentialRequest\x1a&.identity.DeleteUserCredentialResponseB>Z<github.com/k8shell-io/identity/pkg/api/identitypb;identitypbb\x06proto3"

var (
	file_pkg_api_identity_proto_rawDescOnce sync.Once
	file_pkg_api_identity_proto_rawDescData []byte
)

func file_pkg_api_identity_proto_rawDescGZIP() []byte {
	file_pkg_api_identity_proto_rawDescOnce.Do(func() {
		file_pkg_api_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_identity_proto_rawDesc), len(file_pkg_api_identity_proto_rawDesc)))
	})
	return file_pkg_api_identity_proto_rawDescData
}

var file_pkg_api_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_identity_proto_goTypes = []any{
	(*GetUserCredentialsResponse)(nil),         // 0: identity.GetUserCredentialsResponse
	(*AddUserCredentialResponse)(nil),          // 1: identity.AddUserCredentialResponse
	(*UpdateUserCredentialResponse)(nil),       // 2: identity.UpdateUserCredentialResponse
	(*DeleteUserCredentialRequest)(nil),        // 3: identity.DeleteUserCredentialRequest
	(*DeleteUserCredentialResponse)(nil),       // 4: identity.DeleteUserCredentialResponse
	(*commonpb.ExternalCredential)(nil),        // 5: common.ExternalCredential
	(*typespb.FindUserRequest)(nil),            // 6: types.FindUserRequest
	(*typespb.GetUsersRequest)(nil),            // 7: types.GetUsersRequest
	(*typespb.Username)(nil),                   // 8: types.Username
	(*typespb.OnboardUserWebFlowRequest)(nil),  // 9: types.OnboardUserWebFlowRequest
	(*typespb.CompleteUserWebFlowRequest)(nil), // 10: types.CompleteUserWebFlowRequest
	(*typespb.AuthUserPublicKeyRequest)(nil),   // 11: types.AuthUserPublicKeyRequest
	(*typespb.UserStr)(nil),                    // 12: types.UserStr
	(*typespb.RepoPullRequestRequest)(nil),     // 13: types.RepoPullRequestRequest
	(*commonpb.User)(nil),                      // 14: common.User
	(*typespb.UserList)(nil),                   // 15: types.UserList
	(*commonpb.UserOnboardCapability)(nil),     // 16: common.UserOnboardCapability
	(*commonpb.OnboardUserDeviceFlow)(nil),     // 17: common.OnboardUserDeviceFlow
	(*commonpb.OnboardUserWebFlow)(nil),        // 18: common.OnboardUserWebFlow
	(*typespb.AuthUserResponse)(nil),           // 19: types.AuthUserResponse
	(*typespb.Blueprint)(nil),                  // 20: types.Blueprint
	(*typespb.RepoRefResponse)(nil),            // 21: types.RepoRefResponse
}
var file_pkg_api_identity_proto_depIdxs = []int32{
	5,  // 0: identity.GetUserCredentialsResponse.credentials:type_name -> common.ExternalCredential
	5,  // 1: identity.AddUserCredentialResponse.credential:type_name -> common.ExternalCredential
	5,  // 2: identity.UpdateUserCredentialResponse.credential:type_name -> common.ExternalCredential
	6,  // 3: identity.IdentityService.FindUser:input_type -> types.FindUserRequest
	7,  // 4: identity.IdentityService.GetUsers:input_type -> types.GetUsersRequest
	8,  // 5: identity.IdentityService.GetUserOnboardCapability:input_type -> types.Username
	8,  // 6: identity.IdentityService.OnboardUserDeviceFlow:input_type -> types.Username
	9,  // 7: identity.IdentityService.OnboardUserWebFlow:input_type -> types.OnboardUserWebFlowRequest
	10, // 8: identity.IdentityService.CompleteUserWebFlow:input_type -> types.CompleteUserWebFlowRequest
	11, // 9: identity.IdentityService.AuthUserPublicKey:input_type -> types.AuthUserPublicKeyRequest
	12, // 10: identity.IdentityService.GetBlueprintByUserStr:input_type -> types.UserStr
	13, // 11: identity.IdentityService.ResolvePullRequestToRef:input_type -> types.RepoPullRequestRequest
	8,  // 12: identity.IdentityService.GetUserCredentials:input_type -> types.Username
	5,  // 13: identity.IdentityService.AddUserCredential:input_type -> common.ExternalCredential
	5,  // 14: identity.IdentityService.UpdateUserCredential:input_type -> common.ExternalCredential
	3,  // 15: identity.IdentityService.DeleteUserCredential:input_type -> identity.DeleteUserCredentialRequest
	14, // 16: identity.IdentityService.FindUser:output_type -> common.User
	15, // 17: identity.IdentityService.GetUsers:output_type -> types.UserList
	16, // 18: identity.IdentityService.GetUserOnboardCapability:output_type -> common.UserOnboardCapability
	17, // 19: identity.IdentityService.OnboardUserDeviceFlow:output_type -> common.OnboardUserDeviceFlow
	18, // 20: identity.IdentityService.OnboardUserWebFlow:output_type -> common.OnboardUserWebFlow
	14, // 21: identity.IdentityService.CompleteUserWebFlow:output_type -> common.User
	19, // 22: identity.IdentityService.AuthUserPublicKey:output_type -> types.AuthUserResponse
	20, // 23: identity.IdentityService.GetBlueprintByUserStr:output_type -> types.Blueprint
	21, // 24: identity.IdentityService.ResolvePullRequestToRef:output_type -> types.RepoRefResponse
	0,  // 25: identity.IdentityService.GetUserCredentials:output_type -> identity.GetUserCredentialsResponse
	1,  // 26: identity.IdentityService.AddUserCredential:output_type -> identity.AddUserCredentialResponse
	2,  // 27: identity.IdentityService.UpdateUserCredential:output_type -> identity.UpdateUserCredentialResponse
	4,  // 28: identity.IdentityService.DeleteUserCredential:output_type -> identity.DeleteUserCredentialResponse
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_api_identity_proto_init() }
func file_pkg_api_identity_proto_init() {
	if File_pkg_api_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_identity_proto_rawDesc), len(file_pkg_api_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_identity_proto_goTypes,
		DependencyIndexes: file_pkg_api_identity_proto_depIdxs,
		MessageInfos:      file_pkg_api_identity_proto_msgTypes,
	}.Build()
	File_pkg_api_identity_proto = out.File
	file_pkg_api_identity_proto_goTypes = nil
	file_pkg_api_identity_proto_depIdxs = nil
}
