// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/api/types.proto

package typespb

import (
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Username struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Username) Reset() {
	*x = Username{}
	mi := &file_pkg_api_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Username) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Username) ProtoMessage() {}

func (x *Username) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Username.ProtoReflect.Descriptor instead.
func (*Username) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{0}
}

func (x *Username) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserStr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userstr       string                 `protobuf:"bytes,1,opt,name=userstr,proto3" json:"userstr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStr) Reset() {
	*x = UserStr{}
	mi := &file_pkg_api_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStr) ProtoMessage() {}

func (x *UserStr) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStr.ProtoReflect.Descriptor instead.
func (*UserStr) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{1}
}

func (x *UserStr) GetUserstr() string {
	if x != nil {
		return x.Userstr
	}
	return ""
}

type Blueprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlueprintJson string                 `protobuf:"bytes,1,opt,name=blueprint_json,json=blueprintJson,proto3" json:"blueprint_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blueprint) Reset() {
	*x = Blueprint{}
	mi := &file_pkg_api_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blueprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blueprint) ProtoMessage() {}

func (x *Blueprint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blueprint.ProtoReflect.Descriptor instead.
func (*Blueprint) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{2}
}

func (x *Blueprint) GetBlueprintJson() string {
	if x != nil {
		return x.BlueprintJson
	}
	return ""
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*commonpb.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_pkg_api_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{3}
}

func (x *UserList) GetUsers() []*commonpb.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type FindUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserRequest) Reset() {
	*x = FindUserRequest{}
	mi := &file_pkg_api_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserRequest) ProtoMessage() {}

func (x *FindUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserRequest.ProtoReflect.Descriptor instead.
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{4}
}

func (x *FindUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FindUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_pkg_api_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*commonpb.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_pkg_api_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersResponse) GetUsers() []*commonpb.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type AuthUserPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserPublicKeyRequest) Reset() {
	*x = AuthUserPublicKeyRequest{}
	mi := &file_pkg_api_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserPublicKeyRequest) ProtoMessage() {}

func (x *AuthUserPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*AuthUserPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{7}
}

func (x *AuthUserPublicKeyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthUserPublicKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User          *commonpb.User         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	mi := &file_pkg_api_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{8}
}

func (x *AuthUserResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *AuthUserResponse) GetUser() *commonpb.User {
	if x != nil {
		return x.User
	}
	return nil
}

type OnboardUserWebFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardUserWebFlowRequest) Reset() {
	*x = OnboardUserWebFlowRequest{}
	mi := &file_pkg_api_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardUserWebFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardUserWebFlowRequest) ProtoMessage() {}

func (x *OnboardUserWebFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardUserWebFlowRequest.ProtoReflect.Descriptor instead.
func (*OnboardUserWebFlowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{9}
}

func (x *OnboardUserWebFlowRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OnboardUserWebFlowRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type CompleteUserWebFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUserWebFlowRequest) Reset() {
	*x = CompleteUserWebFlowRequest{}
	mi := &file_pkg_api_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUserWebFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUserWebFlowRequest) ProtoMessage() {}

func (x *CompleteUserWebFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUserWebFlowRequest.ProtoReflect.Descriptor instead.
func (*CompleteUserWebFlowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteUserWebFlowRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CompleteUserWebFlowRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetBlueprintByUserStrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blueprint     string                 `protobuf:"bytes,1,opt,name=blueprint,proto3" json:"blueprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlueprintByUserStrResponse) Reset() {
	*x = GetBlueprintByUserStrResponse{}
	mi := &file_pkg_api_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlueprintByUserStrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlueprintByUserStrResponse) ProtoMessage() {}

func (x *GetBlueprintByUserStrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlueprintByUserStrResponse.ProtoReflect.Descriptor instead.
func (*GetBlueprintByUserStrResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlueprintByUserStrResponse) GetBlueprint() string {
	if x != nil {
		return x.Blueprint
	}
	return ""
}

type RepoPullRequestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RepoOwner         string                 `protobuf:"bytes,2,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoName          string                 `protobuf:"bytes,3,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	PullRequestNumber int32                  `protobuf:"varint,4,opt,name=pull_request_number,json=pullRequestNumber,proto3" json:"pull_request_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RepoPullRequestRequest) Reset() {
	*x = RepoPullRequestRequest{}
	mi := &file_pkg_api_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoPullRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoPullRequestRequest) ProtoMessage() {}

func (x *RepoPullRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoPullRequestRequest.ProtoReflect.Descriptor instead.
func (*RepoPullRequestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{12}
}

func (x *RepoPullRequestRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RepoPullRequestRequest) GetRepoOwner() string {
	if x != nil {
		return x.RepoOwner
	}
	return ""
}

func (x *RepoPullRequestRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *RepoPullRequestRequest) GetPullRequestNumber() int32 {
	if x != nil {
		return x.PullRequestNumber
	}
	return 0
}

type RepoRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoRef       string                 `protobuf:"bytes,1,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoRefResponse) Reset() {
	*x = RepoRefResponse{}
	mi := &file_pkg_api_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoRefResponse) ProtoMessage() {}

func (x *RepoRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoRefResponse.ProtoReflect.Descriptor instead.
func (*RepoRefResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_types_proto_rawDescGZIP(), []int{13}
}

func (x *RepoRefResponse) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

var File_pkg_api_types_proto protoreflect.FileDescriptor

const file_pkg_api_types_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/api/types.proto\x12\x05types\x1a\x1ccommon/pkg/gapi/common.proto\"&\n" +
	"\bUsername\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"#\n" +
	"\aUserStr\x12\x18\n" +
	"\auserstr\x18\x01 \x01(\tR\auserstr\"2\n" +
	"\tBlueprint\x12%\n" +
	"\x0eblueprint_json\x18\x01 \x01(\tR\rblueprintJson\".\n" +
	"\bUserList\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.common.UserR\x05users\"C\n" +
	"\x0fFindUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"?\n" +
	"\x0fGetUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"6\n" +
	"\x10GetUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.common.UserR\x05users\"U\n" +
	"\x18AuthUserPublicKeyRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"J\n" +
	"\x10AuthUserResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12 \n" +
	"\x04user\x18\x02 \x01(\v2\f.common.UserR\x04user\"Z\n" +
	"\x19OnboardUserWebFlowRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\"F\n" +
	"\x1aCompleteUserWebFlowRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"=\n" +
	"\x1dGetBlueprintByUserStrResponse\x12\x1c\n" +
	"\tblueprint\x18\x01 \x01(\tR\tblueprint\"\xa0\x01\n" +
	"\x16RepoPullRequestRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"repo_owner\x18\x02 \x01(\tR\trepoOwner\x12\x1b\n" +
	"\trepo_name\x18\x03 \x01(\tR\brepoName\x12.\n" +
	"\x13pull_request_number\x18\x04 \x01(\x05R\x11pullRequestNumber\",\n" +
	"\x0fRepoRefResponse\x12\x19\n" +
	"\brepo_ref\x18\x01 \x01(\tR\arepoRefB8Z6github.com/k8shell-io/identity/pkg/api/typespb;typespbb\x06proto3"

var (
	file_pkg_api_types_proto_rawDescOnce sync.Once
	file_pkg_api_types_proto_rawDescData []byte
)

func file_pkg_api_types_proto_rawDescGZIP() []byte {
	file_pkg_api_types_proto_rawDescOnce.Do(func() {
		file_pkg_api_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_types_proto_rawDesc), len(file_pkg_api_types_proto_rawDesc)))
	})
	return file_pkg_api_types_proto_rawDescData
}

var file_pkg_api_types_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_api_types_proto_goTypes = []any{
	(*Username)(nil),                      // 0: types.Username
	(*UserStr)(nil),                       // 1: types.UserStr
	(*Blueprint)(nil),                     // 2: types.Blueprint
	(*UserList)(nil),                      // 3: types.UserList
	(*FindUserRequest)(nil),               // 4: types.FindUserRequest
	(*GetUsersRequest)(nil),               // 5: types.GetUsersRequest
	(*GetUsersResponse)(nil),              // 6: types.GetUsersResponse
	(*AuthUserPublicKeyRequest)(nil),      // 7: types.AuthUserPublicKeyRequest
	(*AuthUserResponse)(nil),              // 8: types.AuthUserResponse
	(*OnboardUserWebFlowRequest)(nil),     // 9: types.OnboardUserWebFlowRequest
	(*CompleteUserWebFlowRequest)(nil),    // 10: types.CompleteUserWebFlowRequest
	(*GetBlueprintByUserStrResponse)(nil), // 11: types.GetBlueprintByUserStrResponse
	(*RepoPullRequestRequest)(nil),        // 12: types.RepoPullRequestRequest
	(*RepoRefResponse)(nil),               // 13: types.RepoRefResponse
	(*commonpb.User)(nil),                 // 14: common.User
}
var file_pkg_api_types_proto_depIdxs = []int32{
	14, // 0: types.UserList.users:type_name -> common.User
	14, // 1: types.GetUsersResponse.users:type_name -> common.User
	14, // 2: types.AuthUserResponse.user:type_name -> common.User
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_api_types_proto_init() }
func file_pkg_api_types_proto_init() {
	if File_pkg_api_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_types_proto_rawDesc), len(file_pkg_api_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_types_proto_goTypes,
		DependencyIndexes: file_pkg_api_types_proto_depIdxs,
		MessageInfos:      file_pkg_api_types_proto_msgTypes,
	}.Build()
	File_pkg_api_types_proto = out.File
	file_pkg_api_types_proto_goTypes = nil
	file_pkg_api_types_proto_depIdxs = nil
}
