// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/api/idp.proto

package idppb

import (
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	typespb "github.com/k8shell-io/identity/pkg/api/typespb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfoRequest) Reset() {
	*x = ProviderInfoRequest{}
	mi := &file_pkg_api_idp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfoRequest) ProtoMessage() {}

func (x *ProviderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_idp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfoRequest.ProtoReflect.Descriptor instead.
func (*ProviderInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_idp_proto_rawDescGZIP(), []int{0}
}

type ProviderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	UserMaxAge    uint32                 `protobuf:"varint,3,opt,name=user_max_age,json=userMaxAge,proto3" json:"user_max_age,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfoResponse) Reset() {
	*x = ProviderInfoResponse{}
	mi := &file_pkg_api_idp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfoResponse) ProtoMessage() {}

func (x *ProviderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_idp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfoResponse.ProtoReflect.Descriptor instead.
func (*ProviderInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_idp_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderInfoResponse) GetUserMaxAge() uint32 {
	if x != nil {
		return x.UserMaxAge
	}
	return 0
}

func (x *ProviderInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserToken) Reset() {
	*x = UserToken{}
	mi := &file_pkg_api_idp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToken) ProtoMessage() {}

func (x *UserToken) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_idp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToken.ProtoReflect.Descriptor instead.
func (*UserToken) Descriptor() ([]byte, []int) {
	return file_pkg_api_idp_proto_rawDescGZIP(), []int{2}
}

func (x *UserToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pkg_api_idp_proto protoreflect.FileDescriptor

const file_pkg_api_idp_proto_rawDesc = "" +
	"\n" +
	"\x11pkg/api/idp.proto\x12\x03idp\x1a(.proto_deps/common/pkg/gapi/common.proto\x1a\x13pkg/api/types.proto\"\x15\n" +
	"\x13ProviderInfoRequest\"\x8a\x01\n" +
	"\x14ProviderInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12 \n" +
	"\fuser_max_age\x18\x03 \x01(\rR\n" +
	"userMaxAge\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"!\n" +
	"\tUserToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xc7\x05\n" +
	"\x17IdentityProviderService\x12C\n" +
	"\fProviderInfo\x12\x18.idp.ProviderInfoRequest\x1a\x19.idp.ProviderInfoResponse\x120\n" +
	"\bFindUser\x12\x16.types.FindUserRequest\x1a\f.common.User\x12C\n" +
	"\x11OnboardCapability\x12\x0f.types.Username\x1a\x1d.common.UserOnboardCapability\x12G\n" +
	"\x15OnboardUserDeviceFlow\x12\x0f.types.Username\x1a\x1d.common.OnboardUserDeviceFlow\x12R\n" +
	"\x12OnboardUserWebFlow\x12 .types.OnboardUserWebFlowRequest\x1a\x1a.common.OnboardUserWebFlow\x12F\n" +
	"\x13CompleteUserWebFlow\x12!.types.CompleteUserWebFlowRequest\x1a\f.common.User\x12M\n" +
	"\x11AuthUserPublicKey\x12\x1f.types.AuthUserPublicKeyRequest\x1a\x17.types.AuthUserResponse\x12/\n" +
	"\fGetUserToken\x12\x0f.types.Username\x1a\x0e.idp.UserToken\x129\n" +
	"\x15GetBlueprintByUserStr\x12\x0e.types.UserStr\x1a\x10.types.Blueprint\x12P\n" +
	"\x17ResolvePullRequestToRef\x12\x1d.types.RepoPullRequestRequest\x1a\x16.types.RepoRefResponseB4Z2github.com/k8shell-io/identity/pkg/api/idppb;idppbb\x06proto3"

var (
	file_pkg_api_idp_proto_rawDescOnce sync.Once
	file_pkg_api_idp_proto_rawDescData []byte
)

func file_pkg_api_idp_proto_rawDescGZIP() []byte {
	file_pkg_api_idp_proto_rawDescOnce.Do(func() {
		file_pkg_api_idp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_idp_proto_rawDesc), len(file_pkg_api_idp_proto_rawDesc)))
	})
	return file_pkg_api_idp_proto_rawDescData
}

var file_pkg_api_idp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_api_idp_proto_goTypes = []any{
	(*ProviderInfoRequest)(nil),                // 0: idp.ProviderInfoRequest
	(*ProviderInfoResponse)(nil),               // 1: idp.ProviderInfoResponse
	(*UserToken)(nil),                          // 2: idp.UserToken
	(*typespb.FindUserRequest)(nil),            // 3: types.FindUserRequest
	(*typespb.Username)(nil),                   // 4: types.Username
	(*typespb.OnboardUserWebFlowRequest)(nil),  // 5: types.OnboardUserWebFlowRequest
	(*typespb.CompleteUserWebFlowRequest)(nil), // 6: types.CompleteUserWebFlowRequest
	(*typespb.AuthUserPublicKeyRequest)(nil),   // 7: types.AuthUserPublicKeyRequest
	(*typespb.UserStr)(nil),                    // 8: types.UserStr
	(*typespb.RepoPullRequestRequest)(nil),     // 9: types.RepoPullRequestRequest
	(*commonpb.User)(nil),                      // 10: common.User
	(*commonpb.UserOnboardCapability)(nil),     // 11: common.UserOnboardCapability
	(*commonpb.OnboardUserDeviceFlow)(nil),     // 12: common.OnboardUserDeviceFlow
	(*commonpb.OnboardUserWebFlow)(nil),        // 13: common.OnboardUserWebFlow
	(*typespb.AuthUserResponse)(nil),           // 14: types.AuthUserResponse
	(*typespb.Blueprint)(nil),                  // 15: types.Blueprint
	(*typespb.RepoRefResponse)(nil),            // 16: types.RepoRefResponse
}
var file_pkg_api_idp_proto_depIdxs = []int32{
	0,  // 0: idp.IdentityProviderService.ProviderInfo:input_type -> idp.ProviderInfoRequest
	3,  // 1: idp.IdentityProviderService.FindUser:input_type -> types.FindUserRequest
	4,  // 2: idp.IdentityProviderService.OnboardCapability:input_type -> types.Username
	4,  // 3: idp.IdentityProviderService.OnboardUserDeviceFlow:input_type -> types.Username
	5,  // 4: idp.IdentityProviderService.OnboardUserWebFlow:input_type -> types.OnboardUserWebFlowRequest
	6,  // 5: idp.IdentityProviderService.CompleteUserWebFlow:input_type -> types.CompleteUserWebFlowRequest
	7,  // 6: idp.IdentityProviderService.AuthUserPublicKey:input_type -> types.AuthUserPublicKeyRequest
	4,  // 7: idp.IdentityProviderService.GetUserToken:input_type -> types.Username
	8,  // 8: idp.IdentityProviderService.GetBlueprintByUserStr:input_type -> types.UserStr
	9,  // 9: idp.IdentityProviderService.ResolvePullRequestToRef:input_type -> types.RepoPullRequestRequest
	1,  // 10: idp.IdentityProviderService.ProviderInfo:output_type -> idp.ProviderInfoResponse
	10, // 11: idp.IdentityProviderService.FindUser:output_type -> common.User
	11, // 12: idp.IdentityProviderService.OnboardCapability:output_type -> common.UserOnboardCapability
	12, // 13: idp.IdentityProviderService.OnboardUserDeviceFlow:output_type -> common.OnboardUserDeviceFlow
	13, // 14: idp.IdentityProviderService.OnboardUserWebFlow:output_type -> common.OnboardUserWebFlow
	10, // 15: idp.IdentityProviderService.CompleteUserWebFlow:output_type -> common.User
	14, // 16: idp.IdentityProviderService.AuthUserPublicKey:output_type -> types.AuthUserResponse
	2,  // 17: idp.IdentityProviderService.GetUserToken:output_type -> idp.UserToken
	15, // 18: idp.IdentityProviderService.GetBlueprintByUserStr:output_type -> types.Blueprint
	16, // 19: idp.IdentityProviderService.ResolvePullRequestToRef:output_type -> types.RepoRefResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_idp_proto_init() }
func file_pkg_api_idp_proto_init() {
	if File_pkg_api_idp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_idp_proto_rawDesc), len(file_pkg_api_idp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_idp_proto_goTypes,
		DependencyIndexes: file_pkg_api_idp_proto_depIdxs,
		MessageInfos:      file_pkg_api_idp_proto_msgTypes,
	}.Build()
	File_pkg_api_idp_proto = out.File
	file_pkg_api_idp_proto_goTypes = nil
	file_pkg_api_idp_proto_depIdxs = nil
}
