// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/api/idp.proto

package idppb

import (
	context "context"
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	typespb "github.com/k8shell-io/identity/pkg/api/typespb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityProviderService_ProviderInfo_FullMethodName            = "/idp.IdentityProviderService/ProviderInfo"
	IdentityProviderService_FindUser_FullMethodName                = "/idp.IdentityProviderService/FindUser"
	IdentityProviderService_OnboardCapability_FullMethodName       = "/idp.IdentityProviderService/OnboardCapability"
	IdentityProviderService_OnboardUserDeviceFlow_FullMethodName   = "/idp.IdentityProviderService/OnboardUserDeviceFlow"
	IdentityProviderService_OnboardUserWebFlow_FullMethodName      = "/idp.IdentityProviderService/OnboardUserWebFlow"
	IdentityProviderService_CompleteUserWebFlow_FullMethodName     = "/idp.IdentityProviderService/CompleteUserWebFlow"
	IdentityProviderService_AuthUserPublicKey_FullMethodName       = "/idp.IdentityProviderService/AuthUserPublicKey"
	IdentityProviderService_GetUserToken_FullMethodName            = "/idp.IdentityProviderService/GetUserToken"
	IdentityProviderService_GetBlueprintByUserStr_FullMethodName   = "/idp.IdentityProviderService/GetBlueprintByUserStr"
	IdentityProviderService_ResolvePullRequestToRef_FullMethodName = "/idp.IdentityProviderService/ResolvePullRequestToRef"
)

// IdentityProviderServiceClient is the client API for IdentityProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityProviderService defines the gRPC service for identity provider operations
type IdentityProviderServiceClient interface {
	// Provider Information
	ProviderInfo(ctx context.Context, in *ProviderInfoRequest, opts ...grpc.CallOption) (*ProviderInfoResponse, error)
	// FindUser retrieves a user by username. It can be used for authentication and user lookup.
	FindUser(ctx context.Context, in *typespb.FindUserRequest, opts ...grpc.CallOption) (*commonpb.User, error)
	// GetUsers retrieves a list of users with pagination support.
	OnboardCapability(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.UserOnboardCapability, error)
	// OnboardUserDeviceFlow initiates the device flow onboarding process for a user.
	OnboardUserDeviceFlow(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.OnboardUserDeviceFlow, error)
	// OnboardUserWebFlow initiates the web flow onboarding process for a user.
	OnboardUserWebFlow(ctx context.Context, in *typespb.OnboardUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.OnboardUserWebFlow, error)
	// CompleteUserWebFlow completes the web flow onboarding process using the provided state and code.
	CompleteUserWebFlow(ctx context.Context, in *typespb.CompleteUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.User, error)
	// AuthUserPublicKey authenticates a user using a public key and returns the authentication result
	AuthUserPublicKey(ctx context.Context, in *typespb.AuthUserPublicKeyRequest, opts ...grpc.CallOption) (*typespb.AuthUserResponse, error)
	// GetBlueprintByUserStr retrieves a blueprint associated with a user string identifier.
	GetUserToken(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*UserToken, error)
	// ResolvePullRequestToRef resolves a pull request to a repository reference (e.g., branch or commit).
	GetBlueprintByUserStr(ctx context.Context, in *typespb.UserStr, opts ...grpc.CallOption) (*typespb.Blueprint, error)
	// ResolvePullRequestToRef resolves a pull request to a repository reference (e.g., branch or commit).
	ResolvePullRequestToRef(ctx context.Context, in *typespb.RepoPullRequestRequest, opts ...grpc.CallOption) (*typespb.RepoRefResponse, error)
}

type identityProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityProviderServiceClient(cc grpc.ClientConnInterface) IdentityProviderServiceClient {
	return &identityProviderServiceClient{cc}
}

func (c *identityProviderServiceClient) ProviderInfo(ctx context.Context, in *ProviderInfoRequest, opts ...grpc.CallOption) (*ProviderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfoResponse)
	err := c.cc.Invoke(ctx, IdentityProviderService_ProviderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) FindUser(ctx context.Context, in *typespb.FindUserRequest, opts ...grpc.CallOption) (*commonpb.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.User)
	err := c.cc.Invoke(ctx, IdentityProviderService_FindUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) OnboardCapability(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.UserOnboardCapability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.UserOnboardCapability)
	err := c.cc.Invoke(ctx, IdentityProviderService_OnboardCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) OnboardUserDeviceFlow(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*commonpb.OnboardUserDeviceFlow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.OnboardUserDeviceFlow)
	err := c.cc.Invoke(ctx, IdentityProviderService_OnboardUserDeviceFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) OnboardUserWebFlow(ctx context.Context, in *typespb.OnboardUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.OnboardUserWebFlow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.OnboardUserWebFlow)
	err := c.cc.Invoke(ctx, IdentityProviderService_OnboardUserWebFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) CompleteUserWebFlow(ctx context.Context, in *typespb.CompleteUserWebFlowRequest, opts ...grpc.CallOption) (*commonpb.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.User)
	err := c.cc.Invoke(ctx, IdentityProviderService_CompleteUserWebFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) AuthUserPublicKey(ctx context.Context, in *typespb.AuthUserPublicKeyRequest, opts ...grpc.CallOption) (*typespb.AuthUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(typespb.AuthUserResponse)
	err := c.cc.Invoke(ctx, IdentityProviderService_AuthUserPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) GetUserToken(ctx context.Context, in *typespb.Username, opts ...grpc.CallOption) (*UserToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserToken)
	err := c.cc.Invoke(ctx, IdentityProviderService_GetUserToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) GetBlueprintByUserStr(ctx context.Context, in *typespb.UserStr, opts ...grpc.CallOption) (*typespb.Blueprint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(typespb.Blueprint)
	err := c.cc.Invoke(ctx, IdentityProviderService_GetBlueprintByUserStr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderServiceClient) ResolvePullRequestToRef(ctx context.Context, in *typespb.RepoPullRequestRequest, opts ...grpc.CallOption) (*typespb.RepoRefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(typespb.RepoRefResponse)
	err := c.cc.Invoke(ctx, IdentityProviderService_ResolvePullRequestToRef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityProviderServiceServer is the server API for IdentityProviderService service.
// All implementations must embed UnimplementedIdentityProviderServiceServer
// for forward compatibility.
//
// IdentityProviderService defines the gRPC service for identity provider operations
type IdentityProviderServiceServer interface {
	// Provider Information
	ProviderInfo(context.Context, *ProviderInfoRequest) (*ProviderInfoResponse, error)
	// FindUser retrieves a user by username. It can be used for authentication and user lookup.
	FindUser(context.Context, *typespb.FindUserRequest) (*commonpb.User, error)
	// GetUsers retrieves a list of users with pagination support.
	OnboardCapability(context.Context, *typespb.Username) (*commonpb.UserOnboardCapability, error)
	// OnboardUserDeviceFlow initiates the device flow onboarding process for a user.
	OnboardUserDeviceFlow(context.Context, *typespb.Username) (*commonpb.OnboardUserDeviceFlow, error)
	// OnboardUserWebFlow initiates the web flow onboarding process for a user.
	OnboardUserWebFlow(context.Context, *typespb.OnboardUserWebFlowRequest) (*commonpb.OnboardUserWebFlow, error)
	// CompleteUserWebFlow completes the web flow onboarding process using the provided state and code.
	CompleteUserWebFlow(context.Context, *typespb.CompleteUserWebFlowRequest) (*commonpb.User, error)
	// AuthUserPublicKey authenticates a user using a public key and returns the authentication result
	AuthUserPublicKey(context.Context, *typespb.AuthUserPublicKeyRequest) (*typespb.AuthUserResponse, error)
	// GetBlueprintByUserStr retrieves a blueprint associated with a user string identifier.
	GetUserToken(context.Context, *typespb.Username) (*UserToken, error)
	// ResolvePullRequestToRef resolves a pull request to a repository reference (e.g., branch or commit).
	GetBlueprintByUserStr(context.Context, *typespb.UserStr) (*typespb.Blueprint, error)
	// ResolvePullRequestToRef resolves a pull request to a repository reference (e.g., branch or commit).
	ResolvePullRequestToRef(context.Context, *typespb.RepoPullRequestRequest) (*typespb.RepoRefResponse, error)
	mustEmbedUnimplementedIdentityProviderServiceServer()
}

// UnimplementedIdentityProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityProviderServiceServer struct{}

func (UnimplementedIdentityProviderServiceServer) ProviderInfo(context.Context, *ProviderInfoRequest) (*ProviderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProviderInfo not implemented")
}
func (UnimplementedIdentityProviderServiceServer) FindUser(context.Context, *typespb.FindUserRequest) (*commonpb.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUser not implemented")
}
func (UnimplementedIdentityProviderServiceServer) OnboardCapability(context.Context, *typespb.Username) (*commonpb.UserOnboardCapability, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardCapability not implemented")
}
func (UnimplementedIdentityProviderServiceServer) OnboardUserDeviceFlow(context.Context, *typespb.Username) (*commonpb.OnboardUserDeviceFlow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardUserDeviceFlow not implemented")
}
func (UnimplementedIdentityProviderServiceServer) OnboardUserWebFlow(context.Context, *typespb.OnboardUserWebFlowRequest) (*commonpb.OnboardUserWebFlow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardUserWebFlow not implemented")
}
func (UnimplementedIdentityProviderServiceServer) CompleteUserWebFlow(context.Context, *typespb.CompleteUserWebFlowRequest) (*commonpb.User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteUserWebFlow not implemented")
}
func (UnimplementedIdentityProviderServiceServer) AuthUserPublicKey(context.Context, *typespb.AuthUserPublicKeyRequest) (*typespb.AuthUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUserPublicKey not implemented")
}
func (UnimplementedIdentityProviderServiceServer) GetUserToken(context.Context, *typespb.Username) (*UserToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserToken not implemented")
}
func (UnimplementedIdentityProviderServiceServer) GetBlueprintByUserStr(context.Context, *typespb.UserStr) (*typespb.Blueprint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlueprintByUserStr not implemented")
}
func (UnimplementedIdentityProviderServiceServer) ResolvePullRequestToRef(context.Context, *typespb.RepoPullRequestRequest) (*typespb.RepoRefResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePullRequestToRef not implemented")
}
func (UnimplementedIdentityProviderServiceServer) mustEmbedUnimplementedIdentityProviderServiceServer() {
}
func (UnimplementedIdentityProviderServiceServer) testEmbeddedByValue() {}

// UnsafeIdentityProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityProviderServiceServer will
// result in compilation errors.
type UnsafeIdentityProviderServiceServer interface {
	mustEmbedUnimplementedIdentityProviderServiceServer()
}

func RegisterIdentityProviderServiceServer(s grpc.ServiceRegistrar, srv IdentityProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedIdentityProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityProviderService_ServiceDesc, srv)
}

func _IdentityProviderService_ProviderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).ProviderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_ProviderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).ProviderInfo(ctx, req.(*ProviderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.FindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_FindUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).FindUser(ctx, req.(*typespb.FindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_OnboardCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).OnboardCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_OnboardCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).OnboardCapability(ctx, req.(*typespb.Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_OnboardUserDeviceFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).OnboardUserDeviceFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_OnboardUserDeviceFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).OnboardUserDeviceFlow(ctx, req.(*typespb.Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_OnboardUserWebFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.OnboardUserWebFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).OnboardUserWebFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_OnboardUserWebFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).OnboardUserWebFlow(ctx, req.(*typespb.OnboardUserWebFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_CompleteUserWebFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.CompleteUserWebFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).CompleteUserWebFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_CompleteUserWebFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).CompleteUserWebFlow(ctx, req.(*typespb.CompleteUserWebFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_AuthUserPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.AuthUserPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).AuthUserPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_AuthUserPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).AuthUserPublicKey(ctx, req.(*typespb.AuthUserPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_GetUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).GetUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_GetUserToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).GetUserToken(ctx, req.(*typespb.Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_GetBlueprintByUserStr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.UserStr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).GetBlueprintByUserStr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_GetBlueprintByUserStr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).GetBlueprintByUserStr(ctx, req.(*typespb.UserStr))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderService_ResolvePullRequestToRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(typespb.RepoPullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServiceServer).ResolvePullRequestToRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProviderService_ResolvePullRequestToRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServiceServer).ResolvePullRequestToRef(ctx, req.(*typespb.RepoPullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityProviderService_ServiceDesc is the grpc.ServiceDesc for IdentityProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idp.IdentityProviderService",
	HandlerType: (*IdentityProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProviderInfo",
			Handler:    _IdentityProviderService_ProviderInfo_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _IdentityProviderService_FindUser_Handler,
		},
		{
			MethodName: "OnboardCapability",
			Handler:    _IdentityProviderService_OnboardCapability_Handler,
		},
		{
			MethodName: "OnboardUserDeviceFlow",
			Handler:    _IdentityProviderService_OnboardUserDeviceFlow_Handler,
		},
		{
			MethodName: "OnboardUserWebFlow",
			Handler:    _IdentityProviderService_OnboardUserWebFlow_Handler,
		},
		{
			MethodName: "CompleteUserWebFlow",
			Handler:    _IdentityProviderService_CompleteUserWebFlow_Handler,
		},
		{
			MethodName: "AuthUserPublicKey",
			Handler:    _IdentityProviderService_AuthUserPublicKey_Handler,
		},
		{
			MethodName: "GetUserToken",
			Handler:    _IdentityProviderService_GetUserToken_Handler,
		},
		{
			MethodName: "GetBlueprintByUserStr",
			Handler:    _IdentityProviderService_GetBlueprintByUserStr_Handler,
		},
		{
			MethodName: "ResolvePullRequestToRef",
			Handler:    _IdentityProviderService_ResolvePullRequestToRef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/idp.proto",
}
