# values for identity service

# configmap with identity service configuration
# it must exsit in the namespace
configMapName: "identity-config"

# number of identity service replicas to run
replicaCount: 2

# identity service image
image:
  registry: "registry.k8shell.io"
  name: "k8shell-base/identity"
  tag: "1.0"
  imagePullPolicy: Always
  imagePullSecret: regcred

# location of the secrets
secretFiles: "/etc/secrets"

api:
  service:
    ClusterIP:
      port: 9090
