name: Build Identity Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-identity:
    runs-on: k8shell-runner

    env:
      GO111MODULE: on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git for private modules
        run: |
          git config --global url."https://${{ secrets.GH_PAT_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Get version and commit ID
        run: |
          VERSION=$(git describe --tags --match '*' | sed 's/-g.*//')
          COMMIT_ID=$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV

      - name: Install swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: swag init -g main.go -o ./docs

      - name: Vendor Go modules
        run: |
          go mod vendor
          mkdir -p docker/identity/files
          cp -r vendor docker/identity/files/

      - name: Copy sources to docker context
        run: |
          cp go.mod go.sum main.go -t docker/identity/files/
          cp -r pkg internal db docs docker/identity/files/
          echo -n "k8shell-base/identity:$VERSION" > docker/identity/BUILD

      - name: Load REPO_NAME from docker/identity/BUILD
        run: echo "REPO_NAME=$(cat docker/identity/BUILD)" >> $GITHUB_ENV

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: docker/identity
          tags: ${{ secrets.REGISTRY }}/${{ env.REPO_NAME }}
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_ID=${{ env.COMMIT_ID }}