name: Build Identity Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  k8shell-proxy-module:
    runs-on: k8shell-runner

    env:
      GO111MODULE: on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git for private modules
        run: |
          git config --global url."https://${{ secrets.GH_PAT_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Get version
        id: version
        run: |
          VERSION=$(git describe --tags --match '*' | sed 's/-g.*//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "REPO_NAME=$(cat docker/BUILD)" >> $GITHUB_ENV

      - name: Vendor Go modules
        run: |
          mkdir -p docker/files
          go mod vendor -o docker/files/vendor

      - name: Copy sources to docker context
        run: |
          cp go.mod go.sum main.go -t docker/files/
          cp -r pkg internal db docker/files/

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: docker
          tags: ${{ secrets.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_ID=${{ env.COMMIT_ID }}
